trigger:
  branches:
    include: ['*']
  tags:
    include: ['*']


variables:
  nightly: nightly-2019-08-28
  RUSTFLAGS: -Dwarnings

jobs:
# Check formatting
- job: rustfmt
  displayName: Check rustfmt
  steps:
    - template: ci/install-rust.yml
      parameters:
        rust: $(nightly)
        components: ["rustfmt"]
    - script: |
        cargo fmt --all -- --check
      displayName: Check formating

# Apply clippy lints to all crates
- job: clippy
  displayName: Check clippy
  steps:
    - template: ci/install-rust.yml
      parameters:
        rust: $(nightly)
        components: ["clippy"]
    - script: |
        cargo clippy --all
      displayName: Run clippy

- job: check
  displayName: Cargo check
  steps:
    - template: ci/install-rust.yml
      parameters:
        rust: $(nightly)
    - script: |
        cargo check --all
      displayName: Run cargo check

- job: test
  displayName: Cargo test
  steps:
    - template: ci/install-rust.yml
      parameters:
        rust: $(nightly)
    - script: |
        cargo test --all
      displayName: Run cargo tests
