[package]
name = "async-std-tls"
version = "0.1.0"
authors = ["JustinRlle <justin.rerolle@protonmail.com>"]
edition = "2018"
publish = false

[dependencies]
native-tls = "0.2.3"
async-std = "0.99.4"
futures-preview = "0.3.0-alpha.17"
